[tool.poetry]
name = "repl_python3_autobico"
version = "0.1.0"
description = ""
authors = ["sung1eo91 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pyupbit = "^0.2.19"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
